### ISSUE TITLE
Running Script

### ISSUE THREAD

**Issue by guwoop** [sidharthrajaram/nbaszn#5]
Hi,

I'm currently getting the following error, wondering if this is the correct format on running the script. 
python3 predict_game.py 2020, DET, 2020, ATL

x@MacBook-Pro CrystalBall-master % python3 predict_game.py 2020, DET, 2020, ATL
Simulation Presets:
Epochs: 100000
Home Team Variation Range Max: 100
Away Team Variation Range Max: 100

Traceback (most recent call last):
  File "predict_game.py", line 6, in <module>
    simulate_game(sys.argv[1], sys.argv[3], sys.argv[2], sys.argv[4], display_info=True)
  File "/Users/zzz/Desktop/CrystalBall-master/sim.py", line 28, in simulate_game
    t1_metric = team_score(t1_id, t1_year)
  File "/Users/zzzDesktop/CrystalBall-master/sim.py", line 15, in team_score
    df = getTeamDf(team_id, year)
  File "/Users/zzz/Desktop/CrystalBall-master/sim.py", line 10, in getTeamDf
    df_header = get_team_data(team_id, year, header=True)
  File "/Users/zzz/Desktop/CrystalBall-master/utils.py", line 12, in get_team_data
    team_stats_tuple = getTeamStats(team_id, year)
  File "/Users/zzz/Desktop/CrystalBall-master/team_scraper.py", line 14, in getTeamStats
    with urllib.request.urlopen(url) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

thanks,

**Comment by sidharthrajaram** [comment]
Hey there,

Try it without the spaces like so:
`python3 predict_game.py 2020 DET 2020 ATL`

Also just in case, if you're trying to predict games for this season, you will have to use 2021 instead (I'll add this to the readme).
